[tool.poetry]
name = "mldevops-exercise"
version = "0.1.0"
description = ""
authors = ["Michal Strzezon <mstrzezon@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
torch = "^2.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
